package domain

import (
	"encoding/json"
	"time"
)

// RawJSON is an alias for json.RawMessage that marshals as a JSON value
// (not as a base64-encoded string) when embedded in response structs.
type RawJSON = json.RawMessage

// Course represents a top-level learning course that groups related themes.
type Course struct {
	ID             string
	Title          string
	Description    *string
	TargetLanguage string // "en", "it", "ko", "pt"
	SortOrder      int
	CreatedAt      time.Time
}

// Theme represents a conversation topic within a course. It carries the
// target phrases and base vocabulary that the AI uses when generating prompts.
type Theme struct {
	ID             string
	CourseID       string
	Title          string
	Description    *string
	TargetPhrases  json.RawMessage
	BaseVocabulary json.RawMessage
	DifficultyMin  int
	DifficultyMax  int
	SortOrder      int
	CreatedAt      time.Time
}

// Session represents a single conversation practice session between a user
// and the AI on a particular theme.
type Session struct {
	ID         string
	UserID     string
	ThemeID    string
	Difficulty int
	Status     string // "active", "completed", "abandoned"
	StartedAt  time.Time
	EndedAt    *time.Time
	TurnCount  int
	MaxTurns   int
	CreatedAt  time.Time
}

// Turn represents one exchange within a session: the AI speaks, the user
// responds. Either side may be absent while the session is in progress.
type Turn struct {
	ID              string
	SessionID       string
	TurnNumber      int
	AIText          string
	AIAudioURL      *string
	UserText        *string
	UserAudioURL    *string
	InterpretedText *string
	HintUsed        bool
	RepeatUsed      bool
	JaHelpUsed      bool
	ExampleUsed     bool
	CreatedAt       time.Time
}

// UserStats holds aggregated practice statistics for a single user, computed
// from the sessions and turns tables without any additional storage.
type UserStats struct {
	TotalSessions        int
	TotalPracticeMinutes int
	TotalUserTurns       int
	PronunciationFixes   int
}

// LanguageStat holds per-language statistics for a user.
type LanguageStat struct {
	Language      string
	Sessions      int
	LastPracticed *time.Time
}

// Feedback is the post-session analysis generated by the LLM after the
// conversation finishes.
type Feedback struct {
	ID                 string
	SessionID          string
	Achievements       json.RawMessage
	NaturalExpressions json.RawMessage
	Improvements       json.RawMessage
	ConversationTips   json.RawMessage
	ReviewPhrases      json.RawMessage
	CurrentLevel       json.RawMessage
	NextLevelAdvice    *string
	RawLLMResponse     *string
	CreatedAt          time.Time
}
